name: Build

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository And Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y
      
    - name: Build
      run: . "$HOME/.cargo/env" && cargo build --verbose
      
    - name: Run tests
      run: . "$HOME/.cargo/env" && cargo test --verbose
